### ISSUE TITLE
vc++ link /pdbAltPath:%_pdb% causes --compare 'not equivalent'

### ISSUE THREAD

**Issue by lab2k1** [smarttechnologies/peparser#2]
The attached [pdbAltPath.zip](https://github.com/smarttechnologies/peparser/files/3164599/pdbAltPath.zip) is a minimal vc++ 2015 win32 console project with default settings, except (a) c++ / debug info = pdb, minimal rebuild = no, and (b) link / incremental = no in all configs.

I duplicated the 'release|win32' config as 'release -pdbAltPath|win32' and just added the '/pdbAltPath:%_pdb%' switch to the linker command line (which causes the actual path to be stripped from the binary image). After a clean rebuild from scratch, peParser reports the EXEs in 'release' and 'release -pdbAltPath' to be 'not equivalent' (the complete output is copied in peParser-compare.txt inside the attached).

However, I believe that the two files should compare as 'functionally equivalent' in this case.

**Comment by ezolenko2** [comment]
Unfortunately it looks like compiler rearranges things when effective pdb path length differ. In that example changing configuration names to Release1 and Release2 (to make build path length the same, also a requirement) and setting that link option to be the same on both (either with `/pdbAltPath:%_pdb%` or without it) produces equivalent binaries. Having that option differ produces enough rearrangements to get 26% difference (you can see a list of offset and sizes if you add `--verbose` option). 

You can probably use that list to manually estimate if there are meaningful changes depending on your use case -- lots of one-two byte diffs are almost always address shifts, you can check that if you diff disassembly, you'll see lots of addresses shifted by the same value related to PE section sizes.

This is a similar (or the same) effect as build path length differences. Linker makes debug section smaller and lots of address offsets in code are different.

**Comment by lab2k1** [comment]
Thanks for the followup. FWIW Microsoft's old [binDiff.exe](https://support.microsoft.com/sl-si/help/926027/) also gets tripped by this case. Looks like my hopes to automate verification of "_repeatable builds_" will have to wait for another day.
